noaa-alerts:
  sources:
    - guage-id: 'vwbc1'
      name: 'VWBC1 - Sacramento River at Vina-Woodson Bridge (California)'
      source-type: url
      rss-type: alert
      path: 'https://water.weather.gov/ahps2/rss/alert/vwbc1.rss'
      trigger:
          match: 'Highest Projected Forecast Available'
          minor: 180.0
          moderate: 189.5
          major: 190.0
      notifications:
        # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
        - name: 'VWBC1 - Sacramento River at Vina-Woodson Bridge'
          type: 'SlackWebhook'
          content:
            - '*VWBC1 - Sacramento River at Vina-Woodson Bridge Above Threshold 180 ft*'
            - 'https://water.weather.gov/ahps2/hydrograph.php?gage=vwbc1&wfo=sto'
          path: 'https://hooks.slack.com/services/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'
  